name: Alliance Media
favicon: null
layout_spectrum: 0
typography_spectrum: 0.96916
title: Alliance Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f47920'
    - '#ffffff'
    - '#4b4d4d'
    - '#ff0000'
    - '#000000'
  brandStrength: 0
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
